/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package catalogo;

import bean.Flor;
import bean.FlorDAO;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.ResultSet;
import java.sql.SQLException;
import registros.Registros;


/**
 *
 * @author Julia
 */
public class CatalogoFlores extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(CatalogoFlores.class.getName());


    private int idEdicao = 0;

    public CatalogoFlores() {
        initComponents();

    Color verdeFundo = new Color(125, 148, 102); 
    getContentPane().setBackground(verdeFundo);
        int id = 0;

    idEdicao = id;
    carregarPlanta(id);
    }

    public CatalogoFlores(int id) {
        initComponents();
        idEdicao = id;
        carregarPlanta(id);
    }

    private void carregarPlanta(int id) {

        FlorDAO dao = new FlorDAO();

        ResultSet rs = dao.buscarPorId(id);

        try {

            if (rs.next()) {

                txfNome.setText(rs.getString("nome"));
                txfNomeCientifico.setText(rs.getString("nomecientifico"));
                cmbTipo.setSelectedItem(rs.getString("tipo"));
                txfCor.setText(rs.getString("cor"));
                txfAltMedia.setText(
                        String.valueOf(rs.getDouble("altura"))
                );
                txfEmail.setText(rs.getString("email"));
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar planta: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        btnGroupTamanho = new javax.swing.ButtonGroup();
        btnGroupSol = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblNomeCientifico = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        lblTamanho = new javax.swing.JLabel();
        lblSol = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        txfNome = new javax.swing.JTextField();
        txfNomeCientifico = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        txfCor = new javax.swing.JTextField();
        btnradPequena = new javax.swing.JRadioButton();
        btnradMedia = new javax.swing.JRadioButton();
        btnradGrande = new javax.swing.JRadioButton();
        lblAltMedia = new javax.swing.JLabel();
        txfAltMedia = new javax.swing.JTextField();
        lblCm = new javax.swing.JLabel();
        txfEmail = new javax.swing.JTextField();
        btnEscolherFoto = new javax.swing.JButton();
        ckbSombra = new javax.swing.JCheckBox();
        ckbSol = new javax.swing.JCheckBox();
        ckbMeiaSombra = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        lblFotoDaFlor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Catálogo de Plantas e Flores");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 43));

        lblNomeCientifico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNomeCientifico.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeCientifico.setText("Nome científico:");
        getContentPane().add(lblNomeCientifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 100, -1, -1));

        lblNome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome da planta:");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 66, -1, -1));

        lblTipo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("Tipo:");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        lblCor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCor.setForeground(new java.awt.Color(255, 255, 255));
        lblCor.setText("Cor:");
        getContentPane().add(lblCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        lblTamanho.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblTamanho.setForeground(new java.awt.Color(255, 255, 255));
        lblTamanho.setText("Tamanho:");
        getContentPane().add(lblTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lblSol.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblSol.setForeground(new java.awt.Color(255, 255, 255));
        lblSol.setText("Necessidade de sol:");
        getContentPane().add(lblSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 173, -1, -1));

        lblFoto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblFoto.setForeground(new java.awt.Color(255, 255, 255));
        lblFoto.setText("Foto:");
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lblEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail para contato:");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        btnCadastrar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(102, 102, 102));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        txfNome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txfNome.setForeground(new java.awt.Color(255, 255, 255));
        txfNome.addActionListener(this::txfNomeActionPerformed);
        getContentPane().add(txfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 61, 240, -1));

        txfNomeCientifico.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txfNomeCientifico.setForeground(new java.awt.Color(255, 255, 255));
        txfNomeCientifico.addActionListener(this::txfNomeCientificoActionPerformed);
        getContentPane().add(txfNomeCientifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 95, 240, -1));

        cmbTipo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cmbTipo.setForeground(new java.awt.Color(255, 255, 255));
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flor", "Planta ornamental", "Suculenta", "Árvore", "Erva" }));
        cmbTipo.addActionListener(this::cmbTipoActionPerformed);
        getContentPane().add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 160, -1));

        txfCor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txfCor.setForeground(new java.awt.Color(255, 255, 255));
        txfCor.addActionListener(this::txfCorActionPerformed);
        getContentPane().add(txfCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 160, -1));

        btnGroupTamanho.add(btnradPequena);
        btnradPequena.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnradPequena.setForeground(new java.awt.Color(255, 255, 255));
        btnradPequena.setText("Pequena");
        btnradPequena.addActionListener(this::btnradPequenaActionPerformed);
        getContentPane().add(btnradPequena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        btnGroupTamanho.add(btnradMedia);
        btnradMedia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnradMedia.setForeground(new java.awt.Color(255, 255, 255));
        btnradMedia.setText("Média");
        getContentPane().add(btnradMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 100, -1));

        btnGroupTamanho.add(btnradGrande);
        btnradGrande.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnradGrande.setForeground(new java.awt.Color(255, 255, 255));
        btnradGrande.setText("Grande");
        getContentPane().add(btnradGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 100, -1));

        lblAltMedia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAltMedia.setForeground(new java.awt.Color(255, 255, 255));
        lblAltMedia.setText("Altura média:");
        getContentPane().add(lblAltMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        txfAltMedia.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txfAltMedia.setForeground(new java.awt.Color(255, 255, 255));
        txfAltMedia.addActionListener(this::txfAltMediaActionPerformed);
        getContentPane().add(txfAltMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 100, -1));

        lblCm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCm.setForeground(new java.awt.Color(255, 255, 255));
        lblCm.setText("cm");
        getContentPane().add(lblCm, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 50, -1));

        txfEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txfEmail.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 263, -1));

        btnEscolherFoto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEscolherFoto.setForeground(new java.awt.Color(102, 102, 102));
        btnEscolherFoto.setText("Escolher Foto");
        btnEscolherFoto.addActionListener(this::btnEscolherFotoActionPerformed);
        getContentPane().add(btnEscolherFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 208, -1, -1));

        ckbSombra.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ckbSombra.setForeground(new java.awt.Color(255, 255, 255));
        ckbSombra.setText("Sombra");
        getContentPane().add(ckbSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        ckbSol.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ckbSol.setForeground(new java.awt.Color(255, 255, 255));
        ckbSol.setText("Sol");
        getContentPane().add(ckbSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        ckbMeiaSombra.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ckbMeiaSombra.setForeground(new java.awt.Color(255, 255, 255));
        ckbMeiaSombra.setText("Meia-sombra");
        ckbMeiaSombra.addActionListener(this::ckbMeiaSombraActionPerformed);
        getContentPane().add(ckbMeiaSombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblFotoDaFlor.setBackground(new java.awt.Color(204, 204, 255));
        lblFotoDaFlor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblFotoDaFlor.setForeground(new java.awt.Color(255, 255, 255));
        lblFotoDaFlor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFotoDaFlor, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFotoDaFlor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 310, 180));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("--------------------------------------------------------");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 710, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("--------------------------------------------------------");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnradPequenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnradPequenaActionPerformed
        
    }//GEN-LAST:event_btnradPequenaActionPerformed

    private void txfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomeActionPerformed
        String nome = txfNome.getText();
        System.out.println(nome);
    }//GEN-LAST:event_txfNomeActionPerformed

    private void txfNomeCientificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomeCientificoActionPerformed
        String nomeCientifico = txfNomeCientifico.getText();
        System.out.println(nomeCientifico);
    }//GEN-LAST:event_txfNomeCientificoActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        String tipo = cmbTipo.getSelectedItem().toString();
        System.out.println(tipo);
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txfCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCorActionPerformed
        String cor = txfCor.getText();
        System.out.println(cor);
    }//GEN-LAST:event_txfCorActionPerformed

    private void txfAltMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfAltMediaActionPerformed
        double altura = Double.parseDouble(txfAltMedia.getText());
        System.out.println(altura);
    }//GEN-LAST:event_txfAltMediaActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    if (txfNome.getText().isEmpty()
            || txfNomeCientifico.getText().isEmpty()
            || txfCor.getText().isEmpty()
            || txfAltMedia.getText().isEmpty()) {

        JOptionPane.showMessageDialog(this,
                "Preencha todas as informações!");
        return;
    }

    if (!btnradPequena.isSelected()
            && !btnradMedia.isSelected()
            && !btnradGrande.isSelected()) {

        JOptionPane.showMessageDialog(this,
                "Selecione o tamanho da planta!");
        return;
    }

    if (!ckbSol.isSelected()
            && !ckbSombra.isSelected()
            && !ckbMeiaSombra.isSelected()) {

        JOptionPane.showMessageDialog(this,
                "Selecione a necessidade de sol!");
        return;
    }

    double altura;

    try {

        altura = Double.parseDouble(txfAltMedia.getText());

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this,
                "A altura deve conter apenas números!");
        return;
    }

    String cor = txfCor.getText();

    if (!cor.matches("[a-zA-ZÀ-ÿ ]+")) {

        JOptionPane.showMessageDialog(this,
                "A cor deve conter apenas letras!");
        return;
    }

    String email = txfEmail.getText();

    if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.com$")) {

        JOptionPane.showMessageDialog(this,
                "Digite um e-mail válido com .com!");
        return;
    }

    String tamanho = "";

    if (btnradPequena.isSelected()) {
        tamanho = "Pequena";

    } else if (btnradMedia.isSelected()) {
        tamanho = "Média";

    } else if (btnradGrande.isSelected()) {
        tamanho = "Grande";
    }

    String necessidadeSol = "";

    if (ckbSol.isSelected()) {
        necessidadeSol += "Sol pleno";
    }

    if (ckbSombra.isSelected()) {

        if (!necessidadeSol.isEmpty()) {
            necessidadeSol += ", ";
        }

        necessidadeSol += "Sombra";
    }

    if (ckbMeiaSombra.isSelected()) {

        if (!necessidadeSol.isEmpty()) {
            necessidadeSol += ", ";
        }

        necessidadeSol += "Meia-sombra";
    }

    Flor f = new Flor();

    f.setNome(txfNome.getText());
    f.setNomeCientifico(txfNomeCientifico.getText());
    f.setTipo(cmbTipo.getSelectedItem().toString());
    f.setCor(cor);
    f.setAltura(altura);
    f.setTamanho(tamanho);
    f.setNecessidadeSol(necessidadeSol);
    f.setEmail(email);
    f.setFoto(caminhoFoto);
    
    String caminhoPDF = pdf.GeradorPDF.gerarPDF(f);

    FlorDAO fDAO = new FlorDAO();

    if (idEdicao != 0) {

        fDAO.atualizar(f, idEdicao);

        JOptionPane.showMessageDialog(this,
                "Planta atualizada com sucesso!");

    } else {

        fDAO.inserir(f);

        JOptionPane.showMessageDialog(this,
                "Planta cadastrada com sucesso!");
    }

    Registros registros = new Registros();

    registros.setVisible(true);

    this.dispose();
              
    }//GEN-LAST:event_btnCadastrarActionPerformed
 
    
    String caminhoFoto = "";
    private void btnEscolherFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherFotoActionPerformed
        JFileChooser arquivo = new JFileChooser();
    if (arquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        File origem = arquivo.getSelectedFile();
        File pasta = new File("fotos");
    if (!pasta.exists()) {
        pasta.mkdir();
    }
    File destino = new File(pasta, origem.getName());
    try {
        Files.copy(
                origem.toPath(),
                destino.toPath(),
                java.nio.file.StandardCopyOption.REPLACE_EXISTING
        );
        caminhoFoto = destino.getPath();
        ImageIcon imagem = new ImageIcon(caminhoFoto);
        Image img = imagem.getImage();
        img = img.getScaledInstance(
                lblFotoDaFlor.getWidth(),
                lblFotoDaFlor.getHeight(),
                Image.SCALE_SMOOTH
        );
        lblFotoDaFlor.setIcon(new ImageIcon(img));
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,
                "Erro ao salvar a foto: " + e.getMessage());
    }
}
    }//GEN-LAST:event_btnEscolherFotoActionPerformed

    private void ckbMeiaSombraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMeiaSombraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbMeiaSombraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CatalogoFlores().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEscolherFoto;
    private javax.swing.ButtonGroup btnGroupSol;
    private javax.swing.ButtonGroup btnGroupTamanho;
    private javax.swing.JRadioButton btnradGrande;
    private javax.swing.JRadioButton btnradMedia;
    private javax.swing.JRadioButton btnradPequena;
    private javax.swing.JCheckBox ckbMeiaSombra;
    private javax.swing.JCheckBox ckbSol;
    private javax.swing.JCheckBox ckbSombra;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAltMedia;
    private javax.swing.JLabel lblCm;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblFotoDaFlor;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeCientifico;
    private javax.swing.JLabel lblSol;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txfAltMedia;
    private javax.swing.JTextField txfCor;
    private javax.swing.JTextField txfEmail;
    private javax.swing.JTextField txfNome;
    private javax.swing.JTextField txfNomeCientifico;
    // End of variables declaration//GEN-END:variables
}
